# Generated by Django 5.2.3 on 2025-06-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_ingredient_price_recipe_author_recipe_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
