# Generated by Django 5.2.3 on 2025-06-26 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredient_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit', models.CharField(choices=[('tsp', 'Teaspoon'), ('dsp', 'Dessertspoon'), ('tbsp', 'Tablespoon'), ('floz', 'Fluid Ounce'), ('cup', 'Cup'), ('pt', 'Pint'), ('qt', 'Quart'), ('gal', 'Gallon'), ('l', 'Liters'), ('ml', 'Milliliters'), ('g', 'Grams'), ('mg', 'Milligrams')], max_length=4)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='price',
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit', models.CharField(choices=[('$', 'Dollar'), ('€', 'Euro'), ('£', 'Pound')], max_length=4)),
                ('amount', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='quantity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.quantity'),
        ),
    ]
