# Generated by Django 5.2.3 on 2025-06-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_quantity_remove_ingredient_price_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.DurationField(default=None, null=True),
        ),
    ]
